app/models.py
import sqlite3

class DbConection:
    
    def __init__(self,database) -> None:

        self.db_name= database
        self.connection = sqlite3.connect(database,  check_same_thread=False)
        self.cursor = self.connection.cursor()
        self.projectTableName = "project"
        self.roleTableName = "role"
        self.userTableName = "user"
        self.roleUserAsocTableName = "user_role_association_table"

    def getProjects(self):
        getAllProjectsStaments = f'SELECT * FROM {self.projectTableName};'
        res = self.cursor.execute(getAllProjectsStaments)
        return res.fetchall()
    
    def getProjectByName(self, name):
        # sqlite no tiene un buen collate para escapar acentos esto deberia servir en otro sql server
        getProjectsByStaments = f'SELECT * FROM  {self.projectTableName} WHERE project_name COLLATE SQL_Latin1_General_Cp1_CI_AI like ?'
        res = self.cursor.execute(getProjectsByStaments,('%'+name+'%',))
        return res.fetchall()

    def getUsers(self):
        getUsersStaments = f'SELECT {self.userTableName}.*, {self.roleTableName}.name as \'role\' FROM user INNER JOIN {self.roleUserAsocTableName} ON {self.userTableName}.id={self.roleUserAsocTableName}.user_id INNER JOIN {self.roleTableName} ON	{self.roleUserAsocTableName}.role_id = {self.roleTableName}.id;'
        res = self.cursor.execute(getUsersStaments)
        return res.fetchall()

app/__init__.py
from flask import Flask
from config import config
from .models import DbConection

db = DbConection("sitio.db")

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views,helpers

app/main/views.py
from flask import render_template, jsonify
from . import main
from .helpers import userResToDic,projectResToDic
from .. import db


@main.route('/')
def index():
    return render_template('index.html')

@main.route('/proyecto/<name>')
def project(name):
    proyects_res = db.getProjectByName(name)
    users_res = db.getUsers()

    response = {
        "projects": list(map(projectResToDic, proyects_res)),
        "users": list(map(userResToDic,users_res))
        }
    return jsonify(response)

app/templates/base.html
{% block head %}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">

{% block styles %}
<link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{% endblock %}

{% endblock%}

<!-- <a class="navbar-brand" href="#">
    <img src="{{ url_for('static', filename='img/Imagen1.png') }}" alt="" width="30" height="24"
        class="d-inline-block align-text-top">
    Eager Llama
</a> -->

<!-- navbar navbar-dark bg-dark -->
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='favicon.ico') }}" alt="" width="30" height="24"
                class="d-inline-block align-text-top">
            data-lab
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Projects examples
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{{url_for('main.project', name='baño')}}">Proyeto con
                                baño</a>
                        </li>
                        <li><a class="dropdown-item" href="{{url_for('main.project', name='Remodelacion')}}">Project
                                Remodelacion</a></li>
                    </ul>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<div class="container-fluid fade-in">
    <div class="row">
        <div class="col-12">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% for category, message in messages %}

            <div class="col-12 alert {{ category }}" role="alert">
                <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="alert"></button>
                {{ message }}
            </div>
        </div>
    </div>
    {% endfor %}
    {% endwith %}

</div>
{% block page_content %}{% endblock %}
</div>

{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
    crossorigin="anonymous"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>
    var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
    var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
        return new bootstrap.Popover(popoverTriggerEl)
    })
</script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block page_content %}
<div class="container full_height d-flex justify-content-center align-items-center">
    <h1 class="display-1">Data Lab Exercise</h1>
</div>
{% endblock %}